[server]
port = 8080
host = "0.0.0.0"
algorithm = "round-robin"
readTimeout = 30
writeTimeout = 30
idleTimeout = 120
shutdownTimeout = 20

[[backends]]
name = "backend1"
url = "http://backend1:8081"
weight = 1
maxConns = 100

[[backends]]
name = "backend2"
url = "http://backend2:8082"
weight = 1
maxConns = 100

[policies.rateLimit]
enabled = true
requestsPer = 1000
period = 60

[policies.security]
allowedIPs = ["127.0.0.1", "::1", "172.16.0.0/12"]

[policies.transform]
addHeaders = { "X-LoadBalancer" = "true", "X-Environment" = "dev" }
removeHeaders = ["X-Forwarded-For"] 