server:
  address: ":8080"
  admin_enable: true
  admin_path: "/admin"
  read_timeout: 30
  write_timeout: 30
  idle_timeout: 60
  cors_enabled: true
  
backend_pools:
  - name: "web-servers"
    algorithm: "round_robin"
    backends:
      - url: "http://localhost:3001"
        weight: 1
      - url: "http://localhost:3002"
        weight: 2
    health_check:
      path: "/health"
      interval: "30s"
      timeout: "5s"

routing_rules:
  - match:
      host: "example.com"
      path: "/api/*"
    target_pool: "web-servers"
    policies:
      - rate_limit: "100/minute"
  - match:
      path: "/*"
    target_pool: "web-servers"
    policies: []

monitoring:
  prometheus:
    enabled: true
    path: "/metrics"
    port: 9090
  tracing:
    enabled: true
    service_name: "go-loadbalancer"
    service_version: "1.0.0"
    environment: "development"
    endpoint: "localhost:4317"
    sampling_rate: 1.0
    protocol: "grpc"
    secure: false
  logging:
    level: "info"
    format: "json"
    output: "stdout"
    include_trace_id: true
    include_span_id: true
  metrics:
    retention_period: "24h"
    aggregation_interval: "1m"
    max_series: 10000
  alerts:
    error_rate_threshold: 0.05
    latency_threshold: 0.5
    health_check_failures: 3
    resource_usage_threshold: 0.8
