name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
          cache: true

      - name: Check for skip test tag
        id: skip-test
        run: |
          if [[ "${{ github.event.head_commit.message }}" == *"[skip test]"* ]]; then
            echo "skip_test=true" >> $GITHUB_OUTPUT
          else
            echo "skip_test=false" >> $GITHUB_OUTPUT
          fi

      - name: Run tests
        if: steps.skip-test.outputs.skip_test != 'true'
        run: |
          go test -v ./...

      - name: Build
        run: |
          go build -v ./...

      - name: Build Docker image
        run: |
          docker build -t go-loadbalancer .

      - name: Run integration tests
        if: steps.skip-test.outputs.skip_test != 'true'
        run: |
          if [[ "$(go env GOOS)/$(go env GOARCH)" == "linux/amd64" ]]; then
            go test -tags=integration -v -cover ./...
          else
            go test -tags=integration -v -race -cover ./...
          fi

      # - name: Run load tests
      #   if: steps.skip-test.outputs.skip_test != 'true'
      #   run: |
      #     make test-load

  nix-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Setup Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Build with Nix
        run: |
          nix build --no-link --print-build-logs

      - name: Run Nix tests
        if: steps.skip-test.outputs.skip_test != 'true'
        run: |
          nix build .#checks.x86_64-linux.tests --no-link --print-build-logs 